senzing-garage/serve-grpc

.github/workflows/go-proxy-pull.yaml, CHANGELOG.md, Makefile, g2configmgrserver/g2configmgrserver.go, g2configserver/g2configserver.go, g2diagnosticserver/g2diagnosticserver.go, g2engineserver/g2engineserver.go, g2productserver/g2productserver.go, go.mod, go.sum, grpcserver/grpcserver.go, grpcserver/grpcserver_test.go
=> Issue 11.dockter.1

CHANGELOG.md, grpcserver/grpcserver.go
=> Issue 19.dockter.1

CHANGELOG.md, Dockerfile
=> #22 Add Database

README.md
=> Issue 25.dockter.2

g2configmgrserver/g2configmgrserver_test.go, g2configserver/g2configserver_test.go
=> #25 Fix URLs

.github/workflows/make-go-tag.yaml
=> #35 Add make-go-tag.yaml

.github/dependabot.yml, .gitignore, .project, CHANGELOG.md, Dockerfile, README.md, cmd/docs.go, cmd/root.go, doc.go, go.mod, go.sum, package.Dockerfile
=> #39 Savepoint

CHANGELOG.md, Dockerfile, cmd/root.go, go.mod, go.sum, package.Dockerfile
=> Issue 42.dockter.2

Makefile, cmd/root.go, docs/errors.md
=> #47 Fixed silent error

CHANGELOG.md
=> #47 Prepare for versioned release

cmd/root.go, go.mod, go.sum
=> #50 Change method from BoolP() to Bool()

.project, Dockerfile, package.Dockerfile
=> #65 Added equal sign

.github/workflows/go-test.yaml, Dockerfile
Update underlying docker images.
Issue number: #1
=> github-util: Update FROM version

CHANGELOG.md, cmd/github.go, go.mod, go.sum
=> #83 Prepare for versioned release

CHANGELOG.md, README.md, g2configmgrserver/g2configmgrserver.go, g2configmgrserver/g2configmgrserver_test.go, g2configmgrserver/main.go, g2configserver/g2configserver.go, g2configserver/main.go, g2diagnosticserver/g2diagnosticserver.go, g2diagnosticserver/g2diagnosticserver_test.go, g2diagnosticserver/main.go, g2engineserver/g2engineserver.go, g2engineserver/g2engineserver_test.go, g2engineserver/main.go, g2productserver/g2productserver.go, g2productserver/main.go, go.mod, go.sum, grpcserver/grpcserver.go, grpcserver/grpcserver_test.go, grpcserver/main.go
=> Issue 90.dockter.1

CHANGELOG.md, go.mod, go.sum
=> Issue 83.dockter.3

.github/workflows/build-docker-container.yaml, CHANGELOG.md, Dockerfile, g2configserver/g2configserver.go, g2configserver/g2configserver_test.go, go.mod, go.sum
=> Issue 107.dockter.1

cmd/root.go, go.mod, go.sum
=> #113 Refactor context variables

.github/workflows/dependabot-automation.yaml
=> #126 Add shared dependabot automation workflow

CHANGELOG.md, Dockerfile, g2productserver/main.go, go.mod, go.sum
=> Issue 140.dockter.1

cmd/context_darwin.go, cmd/context_linux.go, cmd/context_windows.go, cmd/root.go, go.mod, go.sum
=> #45 Update usage of cobra/viper

CHANGELOG.md
=> #205 Prepare for versioned release

.github/linters/.yaml-lint.yml, .github/workflows/add-labels-standardized.yaml, .github/workflows/add-to-project-garage-dependabot.yaml, .github/workflows/add-to-project-garage.yaml, .github/workflows/dependabot-approve-and-merge.yaml, .github/workflows/docker-build-container.yaml, .github/workflows/docker-push-containers-to-dockerhub.yaml, .github/workflows/go-proxy-pull.yaml, .github/workflows/go-test-darwin.yaml, .github/workflows/go-test-linux.yaml, .github/workflows/go-test-windows.yaml, .github/workflows/gofmt.yaml, .github/workflows/gosec.yaml, .github/workflows/lint-workflows.yaml, .github/workflows/make-go-github-file.yaml, .github/workflows/make-go-tag.yaml
Issue number: senzing-factory/build-resources#69
=> senzing-factory/build-resources#69 add linting

.github/workflows/go-test-linux.yaml
=> update installer version to use senzingapi-runtime

.github/workflows/go-test-darwin.yaml, .github/workflows/go-test-windows.yaml
=> #331 Enable macOS/Windows testing

.dockerignore, makefiles/darwin.mk, makefiles/darwin_x86_64.mk, makefiles/linux.mk, makefiles/linux_x86_64.mk
=> #334 Fix docker build process

Dockerfile
=> #334 Fix file permissions

.github/workflows/go-test-linux.yaml, .github/workflows/golangci-lint.yaml, szdiagnosticserver/szdiagnosticserver_examples_test.go
=> update install inputs

.github/workflows/docker-build-container.yaml, .github/workflows/docker-push-containers-to-dockerhub-manual.yaml, .github/workflows/docker-push-containers-to-dockerhub.yaml
=> add quiet flag

.github/linters/actionlint.yml, .github/workflows/docker-build-container.yaml, .github/workflows/docker-push-containers-to-dockerhub-manual.yaml, .github/workflows/docker-push-containers-to-dockerhub.yaml
=> separate container builds on respective architecture to get around cross platform seg fault

.github/workflows/docker-build-container.yaml, .github/workflows/docker-push-containers-to-dockerhub-manual.yaml, .github/workflows/docker-push-containers-to-dockerhub.yaml
=> pin previous buildx version

grpcserver/grpcserver_basic.go
=> #406 Fix SQLite in-memory

.github/workflows/go-test-linux-tls-mutual.yaml, .github/workflows/go-test-linux-tls-not-used.yaml, .github/workflows/go-test-linux-tls-server-side.yaml
=> #429 TLS testing

.github/workflows/docker-push-containers-to-dockerhub-manual.yaml, .github/workflows/docker-push-containers-to-dockerhub.yaml
Issue number: senzing-factory/github-action-docker-buildx-build#29
=> sign tagged images

.github/workflows/add-labels-standardized.yaml, .github/workflows/add-to-project-garage-dependabot.yaml, .github/workflows/add-to-project-garage.yaml, .github/workflows/docker-push-containers-to-dockerhub-manual.yaml, .github/workflows/docker-push-containers-to-dockerhub.yaml, .github/workflows/go-proxy-pull.yaml, .github/workflows/go-test-linux-tls-mutual.yaml, .github/workflows/go-test-linux-tls-not-used.yaml, .github/workflows/go-test-linux-tls-server-side.yaml, .github/workflows/go-test-linux.yaml, .github/workflows/make-go-github-file.yaml, .github/workflows/make-go-tag.yaml
Issue number: senzing-factory/build-resources#179
=> senzing-factory/build-resources#179 add slack notifications

CHANGELOG.md, httpserver/httpserver_basic.go
=> #473 CORS support
